[package]

name = "capnp"
version = "0.3.2"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "Runtime library for Cap'n Proto serialization"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "http://docs.capnproto-rust.org"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]

[lib]

name = "capnp"
path = "src/lib.rs"

[dependencies]
byteorder = "0.3.11"

[dev-dependencies]
quickcheck = "*"


[features]
rpc = ["gj"]

[dependencies.gj]
version = "*"
optional = true